# add support for a specific user to run VSCode Server
---
- name: install a vs-code server
  hosts: server
  become: true
  gather_facts: false
  vars:
    server_password: blahblahblah

  tasks:
  - name: check hosts online
    ping:

  - name: get installer
    get_url: 
      url: https://code-server.dev/install.sh
      dest: ~/install-vscode-server.sh

  - name: install vscode server
    command: sh ~/install-vscode-server.sh

  - name: setup directories
    file: 
      path: ~/.config/code-server/
      state: directory

  - name: set configuration
    blockinfile:
      backup: 1
      create: 1
      path: ~/.config/code-server/config.yaml
      block: |
        bind-addr: 0.0.0.0:8080
        auth: password
        password: {{ server_password }}
        cert: true

  - name: enable service
    service:
      name: code-server@$USER
      enabled: true
      state: started

  - name: enable firewall rule
    firewalld:
      zone: home
      port: 8080/tcp
      permanent: true
      state: enabled

  - name: reload service firewalld
    service:
      name: firewalld
      state: reloaded
