---
- name: scare uncle john in christchurch
  hosts: uncle.john

  vars:
    - mobilephone: '021123456'
  
  tasks:
  - name: scare him
    scare:
      what: ghost
      state: success
    register: result
    notify: joke
  
  - name: try again
    scare:
      what: dentist
      state: success
    when: result.not_scared
    notify: joke
  
  handlers:
  - name: tell uncle john it was all a joke
    listen: joke
    sms:
      - server: sms-server.example.com
      - number: {{ mobilephone }}
      - message: 'Sorry Uncle John it was all a joke :)'
  