---
# tasks file
- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature
  notify: checkreboot

- name: Enable firewall for Domain, Public and Private profiles
  win_firewall:
    state: enabled
    profiles:
    - Domain
    - Private
    - Public
  tags: enable_firewall

- name: Deploy website to IIS servers
  template:
    src: index.html.j2
    dest: c:\inetpub\wwwroot\index.html

- name: Ensure the webserver is reachable
  win_uri:
    url: http://{{inventory_hostname}}
    status_code: '200'
  