---
- name: delete and cleanup windows VMs
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: check online
    ping:

  - name: destory win1
    virt:
      command: destroy
      name: win1
      state: shutdown

  - name: undefine win1
    virt:
      command: undefine
      name: win1

  # check if winvm pool exists 
  - name: delete winvm pool
    command: virsh pool-destroy winvms
  - name: delete winvm pool 3
    command: virsh pool-undefine winvms

  # check if winvm pool exists
  - name: delete iso pool
    command: virsh pool-destroy isos
  - name: delete iso pool 3
    command: virsh pool-undefine isos

  - name: delete directories
    file: 
      path: /vms/
      state: absent


