---
- name: configure and deploy windows VMs
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: check online
    ping:

  - name: setup directories
    file: 
      path: /vms/
      state: directory
      mode: '0755'
  
  - name: setup directories 2
    file: 
      path: /vms/vm-templates/
      state: directory
      mode: '0755'
  
  - name: setup directories 3
    file: 
      path: /vms/win/
      state: directory
      mode: '0755'

  - name: setup directories 4
    file: 
      path: /vms/isos/
      state: directory
      mode: '0755'

  - name: get windows server 2019 installer
    get_url: 
      url: file:///isos/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso
      dest: /vms/isos/win2019.iso

