---
- name: configure and deploy windows VMs
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: check online
    ping:

  - name: setup directories
    file: 
      path: /vms/
      state: directory
      mode: '0755'
  
  - name: setup directories 2
    file: 
      path: /vms/templates/
      state: directory
      mode: '0755'
  
  - name: setup directories 3
    file: 
      path: /vms/vms/
      state: directory
      mode: '0755'

  - name: setup directories 4
    file: 
      path: /vms/vms/win/
      state: directory
      mode: '0755'

  - name: setup directories 5
    file: 
      path: /vms/isos/
      state: directory
      mode: '0755'

  # - name: get windows server 2019 installer
  #   get_url: 
  #     url: file:///isos/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso
  #     dest: /vms/isos/win2019.iso

  - name: setup win1 VMs
    get_url: 
      url: file:///var/lib/awx/projects/_8__upgradedsniffle/vm-creation/templates/vol-win1-v3.xml
      dest: /vms/templates/vol-win1.xml

  - name: setup win1 VMs 2
    get_url: 
      url: file:///var/lib/awx/projects/_8__upgradedsniffle/vm-creation/templates/win1-v3.xml
      dest: /vms/templates/win1.xml

  - name: setup win1 image
    virt_pool:
      command: define
      name: default
      xml: /vms/templates/vol-win1.xml
      state: active

  - name: define win1
    virt:
      command: define
      xml: /vms/templates/win1.xml
      autostart: yes
