---
- name: enable insights
  become: true
  hosts: all 

  tasks:
  - name: register insights
    command: insights-client --register
    ignore_errors: true

  - name: enable insights schedule
    command: insights-client --enable-schedule
    ignore_errors: true
