---
- name: configure and deploy windows VMs
  become: true
  hosts: all
  gather_facts: true

  tasks:
# Prepare directories
  - name: setup directories
    file: 
      path: '{{ item }}'
      state: directory
      mode: '0755'
    with_items:
    - /vms/templates/
    - /vms/isos/
    - /vms/vms/win/

# Prepare Pools
  - name: setup winvm pools
    command: '{{ item }}'
    with_items:
    - virsh pool-define-as winvms --type dir --target /vms/vms/win/
    - virsh pool-build winvms
    - virsh pool-start winvms
    - virsh pool-autostart winvms
    - virsh pool-define-as isos --type dir --target /vms/isos/
    - virsh pool-build isos
    - virsh pool-start isos
    - virsh pool-autostart isos

#Get Images
  - name: get windows server 2019 installer
    get_url: 
      url: file:///isos/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso
      dest: /vms/isos/win2019.iso

  - name: copy unattended image
    get_url: 
      url: file:///var/lib/awx/projects/_8__upgraded_sniffle/kvm/autounattend/win-unattend.vfd
      dest: /vms/isos/win-unattend.vfd

#win1
  - name: download win1 volume xml
    get_url: 
      url: file:///var/lib/awx/projects/_8__upgraded_sniffle/kvm/templates/vol-win1.xml
      dest: /vms/templates/vol-win1.xml

  # Add check if volume already exists
  - name: setup win1 volume
    command: virsh vol-create winvms /vms/templates/vol-win1.xml
    
  - name: define win1
    virt:
      command: define
      xml: "{{ lookup('template', 'templates/win1.xml') }}"
  
  - name: start win1
    virt: 
      name: win1
      state: running

#win2
  - name: download win2 volume xml
    get_url: 
      url: file:///var/lib/awx/projects/_8__upgraded_sniffle/kvm/templates/vol-win2.xml
      dest: /vms/templates/vol-win2.xml

  # Add check if volume already exists
  - name: setup win2 volume
    command: virsh vol-create winvms /vms/templates/vol-win2.xml
    
  - name: define win2
    virt:
      command: define
      xml: "{{ lookup('template', 'templates/win2.xml') }}"
  
  - name: start win2
    virt: 
      name: win2
      state: running
