---
- name: shutdown win vms
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: check online
    ping:

#win1
  - name: start win1
    virt: 
      name: win1
      state: shutdown

#win2
  - name: start win2
    virt: 
      name: win2
      state: shutdown
