---
- name: configure and deploy windows VMs
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: check online
    ping:

# Prepare directories
  - name: setup directories
    file: 
      path: /vms/vms/win/
      state: directory
      mode: '0755'
  
  #- name: setup directories 2
  - file: 
      path: /vms/templates/
      state: directory
      mode: '0755'

  #- name: setup directories 3
  - file: 
      path: /vms/isos/
      state: directory
      mode: '0755'


# Prepare Pools
  # Add check first then do create pool
  - name: setup winvm pool
    command: virsh pool-define-as winvms --type dir --target /vms/vms/win/
  - name: setup winvm pool 2
    command: virsh pool-build winvms
  - name: setup winvm pool 3
    command: virsh pool-start winvms
  - name: setup winvm pool 4
    command: virsh pool-autostart winvms
  
  # Add check first then create pool
  - name: setup iso pool
    command: virsh pool-define-as isos --type dir --target /vms/isos/
  - name: setup iso pool 2
    command: virsh pool-build isos
  - name: setup iso pool 3
    command: virsh pool-start isos
  - name: setup iso pool 4
    command: virsh pool-autostart isos


#Get Images
  - name: get windows server 2019 installer
    get_url: 
      url: file:///isos/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso
      dest: /vms/isos/win2019.iso

  - name: copy unattended image
    get_url: 
      url: file:///var/lib/awx/projects/_8__upgraded_sniffle/kvm/autounattend/win-unattend.vfd
      dest: /vms/isos/win-unattend.vfd

#win1
  - name: download win1 volume xml
    get_url: 
      url: file:///var/lib/awx/projects/_8__upgraded_sniffle/kvm/templates/vol-win1.xml
      dest: /vms/templates/vol-win1.xml

  # Add check if volume already exists
  - name: setup win1 volume
    command: virsh vol-create winvms /vms/templates/vol-win1.xml
    
  - name: define win1
    virt:
      command: define
      xml: "{{ lookup('template', 'templates/win1.xml') }}"
  
  - name: start win1
    virt: 
      name: win1
      state: running

#win2
  - name: download win2 volume xml
    get_url: 
      url: file:///var/lib/awx/projects/_8__upgraded_sniffle/kvm/templates/vol-win2.xml
      dest: /vms/templates/vol-win2.xml

  # Add check if volume already exists
  - name: setup win2 volume
    command: virsh vol-create winvms /vms/templates/vol-win2.xml
    
  - name: define win2
    virt:
      command: define
      xml: "{{ lookup('template', 'templates/win2.xml') }}"
  
  - name: start win2
    virt: 
      name: win2
      state: running
