# DRAFT UNTESTED
---
- name: Destroy an OpenShift Cluster on AWS
  hosts: all
  become: true

  tasks:
  - name: check online
    ping:

  # - name: check for existing environment setup
  #   stat: path=/openshiftprovision/aws/install/install-config.yaml
  #   register: exists

  # - name: fail if no existing environment
  #   fail: msg="There no existing cluster provisioned"
  #   when: exists.stat.exists == False
    
  # disabled temporaily
  - name: destroy cluster
    command: /openshiftprovision/aws/openshift-install destroy cluster --dir=/openshiftprovision/aws/install --log-level=info

  - name: create destroyer backup directory if it doesn't exist
    file: 
      path: ~/backups/openshiftprovisionbackups/aws/
      state: directory
      mode: '0755'

  - name: backup the cluster install configurations and metadata
    archive:
      path: /openshiftprovision/aws/install
      dest: ~/backups/openshiftprovisionbackups/aws/teardown-backup.{{ ansible_date_time.iso8601_basic_short }}.tgz

  - name: delete openshift directories
    file: 
      path: /openshiftprovision/aws/
      state: absent

  - name: delete aws credentials
    file: 
      path: ~/.aws/credentials
      state: absent
