---
- name: upgrade all machines
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
  - name: update and upgrade
    yum:
      name: '*'
      state: latest

  #add check for new kernel and reboot task
