---
- name: upgrade all machines
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
  - name: update and upgrade
    yum:
      name: '*'
      state: latest

  - name: check to see if we need a reboot
    command: needs-restarting -r
    register: result
    ignore_errors: yes

  - name: display result
    debug:
      var: result.rc

  - name: Reboot Server if Necessary
    reboot:
      reboot_timeout: 3600
    when: result.rc == 1

  - name: Wait for connection to nodes
    wait_for_connection:
      timeout: 3600
    when: result.rc == 1

  - name: Ensure online
    setup:
    when: result.rc == 1
