---
# tasks file for apache-simple
- name: install httpd packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ httpd_packages }}"
  notify: restart apache service

- name: copy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart apache service

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: 'yes'
