---
# handlers file for apache-simple

- name: set firewall
  listen: set firewall
  firewalld:
    port: 80/tcp
    permanent: 'yes'
    state: enabled

- name: restart apache service
  listen: restart apache service
  service:
    name: httpd
    state: restarted
    enabled: 'yes'

