---
- name: Auto-subscribe to available content, upgrade and reboot
  hosts: rhel
  become: true
  vars:
    sub_user_name: xxxxx
    sub_password: xxxxx

  tasks:
  - name: update redhat subscription
    redhat_subscription:
      state: present
      username: {{ sub_user_name }}
      password: {{ subpassword }}
      auto_attach: true
      syspurpose:
        usage: "Development/Test"
        role: "Red Hat Enterprise Linux Server"
        service_level_agreement: "Standard"
        sync: true

  - name: update and upgrade
    yum:
      name: '*'
      state: latest
  
  - name: reboot
    reboot:
      reboot_timeout: 3600
