---
- name: Auto-subscribe to available content, upgrade and reboot
  hosts: rhel
  become: true
  vars:
    sub_user_name: xxxxx
    sub_password: xxxxx
    usage: "Development/Test"
    role: "Red Hat Enterprise Linux Server"
    service_level_agreement: "Standard"
    sync: true

  tasks:
  - name: update redhat subscription
    redhat_subscription:
      state: present
      username: {{ sub_user_name }}
      password: {{ subpassword }}
      auto_attach: true
      syspurpose:
        usage: {{ usage }}
        role: {{ role }}
        service_level_agreement: {{ service_level_agreement }}
        sync: {{ sync }}

  - name: update and upgrade
    yum:
      name: '*'
      state: latest
  
  - name: reboot
    reboot:
      reboot_timeout: 3600
