---
- name: Register as user (xxxxx) with password (xxxxx) and auto-subscribe to available content
  hosts: webservers
  become: 'yes'

  tasks:
  - redhat_subscription:
    state: present
    username: xxxxx
    password: xxxxx
    auto_attach: 'true'
    syspurpose:
      usage: "Development/Test"
      role: "Red Hat Enterprise Linux Server"
      service_level_agreement: "Standard"
      sync: 'true'
