---
- name: Register as user (xxxxx) with password (xxxxx) and auto-subscribe to available content.
  hosts: webservers
  become: 'yes'

  tasks:
  redhat_subscription:
    state: present
    username: xxxxx
    password: xxxxx
    auto_attach: 'true'
