---
- name: Register as user (xxxxx) with password (xxxxx), auto-subscribe to available content, upgrade and reboot
  hosts: rhel
  become: 'yes'

  tasks:
  - name: update redhat subscription
    redhat_subscription:
      state: present
      username: xxxxx
      password: xxxxx
      auto_attach: 'true'
      syspurpose:
        usage: "Development/Test"
        role: "Red Hat Enterprise Linux Server"
        service_level_agreement: "Standard"
        sync: 'true'

  - name: update and upgrade
    yum:
      name: '*'
      state: latest
  
  - name: reboot
    reboot:
      reboot_timeout: 3600
