---
- name: install common applications
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: check online
    ping:

- name: Install 7-Zip
  win_chocolatey:
    name: 7zip
    state: present

- name: Install Chrome
  win_chocolatey:
    name: googlechrome
    state: present
 
- name: Install Git
  win_chocolatey:
    name: git.install
    state: present
    