---
- name: Windows Webserver Playbook
  hosts: webservers
  become: true

  tasks:
  - name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature
  notify: checkreboot

- name: Enable firewall for Domain, Public and Private profiles
  win_firewall:
    state: enabled
    profiles:
    - Domain
    - Private
    - Public
  tags: enable_firewall

- name: Ensure the webserver is reachable
  win_uri:
    url: http://{{inventory_hostname}}
    status_code: '200'
  
  handlers:
  - name: Reboot if installing Web-Server feature requires it
  listen: checkreboot
  win_reboot:
  when: win_feature.reboot_required
