---
- name: install common applications
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: check online
    win_ping:

  - name: Install applications
    win_chocolatey:
      name: 
       - 7zip
       #- git
       #- googlechrome
      state: present

