---
- name: install common applications
  become: true
  hosts: all
  gather_facts: true

  tasks:
  - name: Install applications
    win_chocolatey:
      name: 
       - 7zip
       - git
       - googlechrome
      state: present

