---
- name: waiting for provision to complete
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: Wait for connection to nodes
    wait_for_connection:
      timeout: 3600

  - name: Gather facts for first time
    setup:
