---
- name: restart machines
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: For connection
    wait_for_connection:
      delay: 300
      timeout: 3600

  - name: Gather facts for first time
    setup:
