---
- name: configure windows remote desktop
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: Enable Remote Desktop Feature
    win_feature:
      name: Remote-Desktop-Services
      state: present
    register: _windows_remote_desktop_services_enabled
  
  - name: Firewall rule to allow RDP on TCP port 3389
    win_firewall_rule:
      name: Remote Desktop
      localport: '3389'
      action: allow
      direction: in
      protocol: tcp
      profiles: private
      state: present
      enabled: yes
