# DRAFT UNTESTED
---
- name: Install an OpenShift Cluster on AWS
  hosts: all
  become: true

  tasks:
  - name: check online
    ping:

  - name: check for existing environment setup
    stat: path=/openshiftprovision/install/install-config.yaml
    register: exists

  - name: fail if no existing environment
    fail: msg="There no existing cluster provisioned"
    when: exists.stat.exists == False
    
  # disabled temporaily
  - name: destroy cluster
    command: /openshiftprovision/openshift-install destroy cluster --help #--dir=/openshiftprovision/install --log-level=info

  - name: create destroyer backup directory if it doesn't exist
    file: 
      path: ~/openshiftprovisionbackups/
      state: directory
      mode: '0755'

  - name: backup the cluster install configurations and metadata
    archive:
      path: /openshiftprovision/install
      dest: ~/openshiftprovisionbackups/teardown-backup.{{ ansible_date_time.iso8601_basic_short }}.tgz

  - name: delete openshift directories
    file: 
      path: /openshiftprovision
      state: absent

  - name: delete aws credentials
    file: 
      path: ~/.aws/credentials
      state: absent
