# DRAFT UNTESTED 
---
- name: Install an OpenShift Cluster on AWS
  hosts: all
  become: true
  vars:
    cluster_name:           'ocp'
    base_domain:            'domain.com'
    region:                 'ap-southeast-2'
    worker_replicas:        '2'
    pull_secret:            '{"auths":{"cloud.openshift.com":{"auth":"blahblah"}}}'
    sshkey:                 'ssh-rsa blahblah'
    aws_access_key_id:      'blahblah'
    aws_secret_access_key:  'blahblahblah'

  tasks:
  - name: check online
    ping:

  - name: check for existing environment setup
    stat: path=/openshiftprovision/aws/install/install-config.yaml
    register: exists

  - name: fail if existing environment
    fail: msg="There is an existing cluster provisioned or a teardown failed"
    when: exists.stat.exists
    
  - name: create openshift directories
    file: 
      path: /openshiftprovision/aws/install/
      state: directory
      mode: '0755'
  - name: create aws credentials directory
    file: 
      path: ~/.aws/
      state: directory
      mode: '0755'
  - name: create installer backup directory if it doesn't exist
    file: 
      path: ~/openshiftprovisionbackups/aws/
      state: directory
      mode: '0755'

  - name: download installer 4.5 and extract
    unarchive:
      src: file:///isos/openshift-install-linux.tar.gz
      dest: /openshiftprovision/aws/
      remote_src: yes

  - name: create the install-config.yaml
    blockinfile:
      backup: 1
      create: 1
      path: /openshiftprovision/aws/install/install-config.yaml
      block: |
        apiVersion: v1
        baseDomain: {{ base_domain }}
        compute:
        - architecture: amd64
          hyperthreading: Enabled
          name: worker
          platform: 
            aws:
              type: m5.large
          replicas: {{ worker_replicas }}
        controlPlane:
          architecture: amd64
          hyperthreading: Enabled
          name: master
          platform: 
            aws:
              type: m5.xlarge
          replicas: 3
        metadata:
          creationTimestamp: null
          name: {{ cluster_name }}
        networking:
          clusterNetwork:
          - cidr: 10.128.0.0/14
            hostPrefix: 23
          machineNetwork:
          - cidr: 10.0.0.0/16
          networkType: OpenShiftSDN
          serviceNetwork:
          - 172.30.0.0/16
        platform:
          aws:
            region: {{ region }}
        publish: External
        pullSecret: '{{ pull_secret }}'
        sshKey: |
          {{ sshkey }}

# need to do this as seperate lines so block markers aren't added
  - name: create AWS credentials file
    lineinfile:
      backup: 1
      create: 1
      path: ~/.aws/credentials
      line: "; https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html"
  - name: add default line to AWS credentials file
    lineinfile:
      path: ~/.aws/credentials
      line: "[default]"
  - name: add access ID to AWS credentials file
    lineinfile:
      path: ~/.aws/credentials
      line: "aws_access_key_id     = {{ aws_access_key_id }}"
  - name: add access key to AWS credentials file
    lineinfile:
      path: ~/.aws/credentials
      line: "aws_secret_access_key = {{ aws_secret_access_key }}"
  
  # disabled temporaily (added --help)
  - name: install cluster
    command: /openshiftprovision/aws/openshift-install create cluster --help #--dir=/openshiftprovision/install --log-level=info

  - name: backup the cluster install configurations and metadata
    archive:
      path: /openshiftprovision/aws/install
      dest: ~/backups/openshiftprovisionbackups/aws/install-backup.{{ ansible_date_time.iso8601_basic_short }}.tgz
