# DRAFT UNTESTED
---
- name: Install an OpenShift Cluster on AWS
  hosts: all
  become: true
  vars:
    pull_secret: 'xxxxx'
    sshkey: 'xxxxx'
    aws_access_key_id: 'xxxxx'
    aws_secret_access_key: 'xxxxx'

  tasks:
  - name: check online
    ping:

  - name: setup directories
    file: 
      path: /openshiftprovision/install/
      state: directory
      mode: '0755'

  - name: setup directories2
    file: 
      path: ~/.aws/
      state: directory
      mode: '0755'

  - name: download installer 4.5 to directory and extract
    unarchive:
      src: file:///isos/openshift-install-linux.tar.gz
      dest: /openshiftprovision/
      remote_src: yes

  - name: get install-config.yaml
    get_url: 
      url: file:///var/lib/awx/projects/_8__upgraded_sniffle/openshift/aws/install-config.yaml
      dest: /openshiftprovision/install/install-config.yaml
  
  - name: update install config file with pull secret
    lineinfile:
      backup: 1
      path: /openshiftprovision/install/install-config.yaml
      line: "pullSecret: {{ pull_secret }}"

  - name: update install config file with ssh public key
    lineinfile:
      backup: 1
      path: /openshiftprovision/install/install-config.yaml
      line: "sshKey: |"
  - name: update install config file with ssh public key 2
    lineinfile:
      backup: 1
      path: /openshiftprovision/install/install-config.yaml
      line: " {{ sshkey }}"

  - name: create AWS profile
    lineinfile:
      backup: 1
      create: 1
      path: ~/.aws/credentials
      line: "; https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html"
  - name: create AWS profile 2
    lineinfile:
      path: ~/.aws/credentials
      line: "[default]"
  - name: create AWS profile 3
    lineinfile:
      path: ~/.aws/credentials
      line: "aws_access_key_id     = {{ aws_access_key_id }}"
  - name: create AWS profile 4
    lineinfile:
      path: ~/.aws/credentials
      line: "aws_secret_access_key = {{ aws_secret_access_key }}"
        
  # - name: install cluster
  #   command: ./openshiftprovision/openshift-install create cluster --dir=/openshiftprovision/install

