---
- name: backup ansible tower
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: check hosts online
    ping:

  - name: backup tower
    command: sh ./home/awp/Downloads/ansible-tower-setup-3.7.2-1/setup.sh -e 'backup_dest=/home/awp/backups/' -b
