---
- name: backup ansible tower
  become: true
  hosts: all
  gather_facts: false

  tasks:
  - name: check hosts online
    ping:

  - name: backup directory if it doesn't exist
    file: 
      path: ~/backups/ansible/
      state: directory
      mode: '0755'

  - name: backup tower
    command: sh ~/ansible-tower-setup-3.7.2-1/setup.sh -e 'backup_dest=~/backups/ansible' -b